[prerules]
UNIT_DIRS=.. ../* ../../third-party/* ../../utils/* ../../wrappers/*
UNITS=feeditem feed nonxml esf rss3 saxcallbacks xml dc atom rss

[rules]
include ../../../scripts/common.make

all:
	$(RM) ../protocols/httpcache$(OEXT) ../protocols/httpcache$(PPUEXT)
	$(MAKE) httpcache deps
	$(MAKE) $(addsuffix $(PPUEXT), $(UNITS))

install:

deps:
	cd ../protocols && $(MAKE) formatsdeps

httpcache:
	$(MAKE) ../protocols/httpcache.pas
