[prerules]
UNIT_DIRS=.. ../* ../../third-party/* ../../utils/*
UNITS=feeditem feed nonxml esf rss3 xml dc rss atom

[rules]
include ../../../scripts/common.make

all:
	$(MAKE) httpcache deps
	$(MAKE) $(addsuffix $(PPUEXT), $(UNITS))

install:

deps:
	cd ../protocols && $(MAKE) formatsdeps

httpcache:
	$(MAKE) ../protocols/httpcache.pas
