#!/bin/sh

cd `dirname $0`

rm -fv ./Output/* ../r3r-src*.bz2

read VERSION < version.txt

mkdir ../r3r-src-$VERSION
cp -frv * ../r3r-src-$VERSION

cd ..

tar cjvf r3r-src-$VERSION.tar.bz2 r3r-src-$VERSION

rm -frv r3r-src-$VERSION
