#! /bin/sh

# Get the parent directory (for relocatability)
origdir=`pwd`
bindir=$(dirname $(readlink -e $0))
cd $bindir
cwd=`pwd`
bindir=`echo $bindir | sed -e "s|^\(\.\+\)|$cwd/\1|"`
cd ..
parentdir=`pwd`
cd $origdir

R3R_INSTALLED_PREFIX=$parentdir
export R3R_INSTALLED_PREFIX
export LD_LIBRARY_PATH=$parentdir/lib:$LD_LIBRARY_PATH

# If there's an error
err()
{
    (zenity --error --text="$1" || xmessage "$1") 2>/dev/null || echo "$1" >&2
}

# Start up the preferred UI if defined
if test -n "$R3R_UI";
then
    $bindir/r3r-$R3R_UI "$@"
else
    false
fi

# There was an error or no preferred UI is defined
if test $? -ne 0;
then
    $bindir/r3r-wx "$@" || $bindir/r3r-tui "$@" || $bindir/r3r-html "$@" || err "Cannot start any UI"
fi
