#! /bin/sh

# Get the parent directory (for relocatability)
origdir=`pwd`
bindir=`dirname $0`
cd $bindir
cwd=`pwd`
bindir=`echo $bindir | sed -e "s|^\(\.\+\)|$cwd/\1|"`
cd ..
parentdir=`pwd`
cd $origdir

R3R_INSTALLED_PREFIX=$parentdir
export R3R_INSTALLED_PREFIX

# If there's an error
err()
{
  if test -z "$DISPLAY";
  then
    # If there's no X display, just write the error to the screen
    echo "$1"
  else
    # Under X, try the faster and more featured Zenity.
    # If it fails, fall back on xmessage.
    zenity --error --text="$1" || xmessage "$1"
  fi
}

# Start up the preferred UI if defined
if test -n "$R3R_UI";
then
  $bindir/r3r-$R3R_UI "$@"
else
  false
fi

# There was an error or no preferred UI is defined
if test $? -ne 0;
then
  $bindir/r3r-wx "$@" || $bindir/r3r-tui "$@" || $bindir/r3r-html "$@" || err "Cannot start any UI"
fi
