[prerules]
$(shell $(TOUCH) r3r.lpr)

UNIT_DIRS=po ../../libr3r ../../libr3r/* ../../third-party/*

[rules]
include ../../../scripts/common.make

all:
	cd ../../libr3r && $(MAKE) info.pas
	cd po && $(MAKE)
	$(MAKE) classic$(PPUEXT)
	$(PC) $(PCFLAGS) r3r.lpr

clean:
	cd po && $(MAKE) clean
	$(DEL) $(wildcard *.or) $(wildcard *.res)

all:
	cd po && $(MAKE)
	$(PC) r3r.lpr

uninstall:
	cd po && $(MAKE) uninstall
	rm -f $(INSTALL_BINDIR)/r3r$(EXEEXT)
