[prerules]
UNIT_DIRS = ../../third-party/*

[rules]
include ../../../scripts/common.make

all: r3r_opml$(PPUEXT)
	cd po && $(MAKE) all

clean:
	cd po && $(MAKE) clean
	$(DEL) r3r_opml$(EXEEXT)

install:
	cd po && $(MAKE) install
	$(INSTALLEXE) r3r_opml$(EXEEXT) $(bindir)

uninstall:
	cd po && $(MAKE) uninstall
	$(DEL) $(bindir)/r3r_opml$(EXEEXT)
