[prerules]
UNIT_DIRS=po ../../libr3r ../../libr3r/* ../../third-party/* \
					../../utils/* ../../wrappers/*

[rules]
include ../../../scripts/common.make
all:
	$(MAKE) rhtml$(PPUEXT) r3r$(PPUEXT)

install:

uninstall:
