all:
	cd api && $(MAKE) all
	cd man && $(MAKE) html

install:
	cd api && $(MAKE) install
	cd man && $(MAKE) install

uninstall:
	cd api && $(MAKE) uninstall
	cd man && $(MAKE) uninstall

clean:
	cd api && $(MAKE) clean
	cd man && $(MAKE) clean
