all:
	cd rlist && $(MAKE) all
	cd rstrings && $(MAKE) all
	cd strtok && $(MAKE) all
	cd rdate && $(MAKE) all
	cd tabfiles && $(MAKE) all

clean:
	cd rdate && $(MAKE) clean
	cd rlist && $(MAKE) clean
	cd rstrings && $(MAKE) clean
	cd strtok && $(MAKE) clean
	cd tabfiles && $(MAKE) clean
