#!/bin/sh

cd `dirname $0`

CVERSION=`cat ../version.php`
VERSION=`echo $CVERSION|grep -o "[0-9][^']*"`

export VERSION

./prepdist

cd ..

mkdir -p ../r3r-linux-$VERSION/icons
mkdir    ../r3r-linux-$VERSION/includes
mkdir    ../r3r-linux-$VERSION/l10n

cp -fv *.in *.php Artistic README install-sh ../r3r-linux-$VERSION
cp -fv icons/r3r.png ../r3r-linux-$VERSION/icons
cp -fv includes/* ../r3r-linux-$VERSION/includes
cp -fv l10n/*.lng ../r3r-linux-$VERSION/l10n

rm -fv config.status
makeinstaller
mv -fv r3r-$VERSION.x86.package ../r3r-linux-$VERSION.package

cd ..

tar cjvf r3r-linux-$VERSION.tar.bz2 r3r-linux-$VERSION

rm -frv r3r-linux-$VERSION
