#!/bin/sh

cd `dirname $0`

./prepdist

rm -frv Output

cd ..

CVERSION=`cat version.php`
VERSION=`echo $CVERSION|grep -o "[0-9][^']*"`

mkdir ../r3r-src-$VERSION
cp -frv * ../r3r-src-$VERSION

cd ..

tar cjvf r3r-src-$VERSION.tar.bz2 r3r-src-$VERSION

rm -frv r3r-src-$VERSION
