#!/bin/sh

cd `dirname $0`

rm -fv ./Output/* ../../r3r-*.exe

CVERSION=`cat ../version.php`
VERSION=`echo $CVERSION|grep -o "[0-9][^']*"`

export VERSION

compil32 setup.iss /ss

mv Output/setup.exe ../../r3r-win-$VERSION.exe 

rmdir Output
