[prerules]
CC ?= gcc
COBJEXT = .o

UNIT_DIRS=../../utils/*

[rules]
include ../../../scripts/common.make
all: sockwrapc$(COBJEXT) sockwrap$(PPUEXT)

clean:
	$(RM) $(wildcard *$(COBJEXT))

sockwrap.pas: sockwrapc.c
	$(TOUCH) $@

%$(COBJEXT): %.c
	$(CC) -c -o $@ $<

%.c: %.h
	$(TOUCH) $@
