[prerules]
UNIT_DIRS=po ../../libr3r ../../libr3r/* ../../third-party/* ../../utils/*

[rules]
include ../../../scripts/common.make
all:
	cd po && $(MAKE)
	cd ../../libr3r && $(MAKE) info.pas
	$(MAKE) tv$(PPUEXT) r3r$(PPUEXT)

clean:
	cd po && $(MAKE) clean
	$(DEL) $(wildcard *.or) $(wildcard *.res)

install:
	cd po && $(MAKE) intall

uninstall:
	cd po && $(MAKE) uninstall
