all:
	cd $(R3R_UI) && $(MAKE) all

install:
	cd $(R3R_UI) && $(MAKE) install

uninstall:
	cd $(R3R_UI) && $(MAKE) uninstall

clean:
	cd $(R3R_UI) && $(MAKE) clean

distclean:
	cd $(R3R_UI) && $(MAKE) distclean
