#include "wx.h"

enum
{
  wxID_1 = wxID_HIGHEST,
  wxID_ADD_SUBSCRIPTION,
  wxID_BROWSE,
  wxID_CHECK_UPDATES,
  wxID_CONTACT_BUTTON,
  wxID_DELETE_SUBSCRIPTION,
  wxID_DONATE,
  wxID_GO_BUTTON,
  wxID_LOAD_SUBSCRIPTIONS,
  wxID_SETTINGS,
  wxID_SUBSCRIBE_BUTTON,
};
